---
- name: Reconfigure gitlab
  ansible.builtin.command: gitlab-ctl reconfigure
  register: gitlab_restart
  failed_when: gitlab_restart.rc != 0
  tags: skip_ansible_lint

- name: Restart gitlab-runsvdir service
  ansible.builtin.command: gitlab-ctl restart gitlabrunsvdir
  tags: skip_ansible_lint
