---
- name: Converge
  hosts: all
  become: true
  roles:
    - nephelaiio.gitlab
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family | lower == 'debian'
      changed_when: false

    - name: Update yum cache
      ansible.builtin.dnf:
        update_only: true
      when: ansible_os_family | lower == 'redhat'
      changed_when: false

    - name: Remove dockerenv
      ansible.builtin.file:
        path: /.dockerenv
        state: absent
