---
- name: Backup and restore
  hosts: all
  tasks:
    - name: Verify frontpage redirect
      ansible.builtin.uri:
        url: http://localhost
        follow_redirects: none
        status_code: 302
      register: _frontpage_redirect
      until: _frontpage_redirect is not failed
      retries: 12
      delay: 15

    - name: Verify frontpage content
      ansible.builtin.uri:
        url: http://localhost
        status_code: 200
      register: _frontpage_content
      until: _frontpage_content is not failed
      retries: 12
      delay: 15

    - name: Verify status command before backup
      ansible.builtin.command: gitlab-ctl status

    - name: Take gitlab backup
      ansible.builtin.command: /usr/local/bin/gitlab-backup

    - name: Disable connections to gitlab database
      ansible.builtin.command: 'gitlab-psql -d postgres -c "update pg_database set datallowconn = false where datname = ''gitlabhq_production''"'

    - name: Disconnect users from gitlab database
      ansible.builtin.command: 'gitlab-psql -d postgres -c "select pg_terminate_backend(pid) from pg_stat_activity where datname=''gitlabhq_production''"'

    - name: Drop gitlab database
      ansible.builtin.command: gitlab-psql -d postgres -c "DROP DATABASE gitlabhq_production;"

    - name: Delete gitlab configuration files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/gitlab/gitlab.rb
        - /etc/gitlab/gitlab-secrets.json

    - name: Verify gitlab database removal
      ansible.builtin.command: 'gitlab-psql -d postgres -t -c "select json_agg(datname) from pg_database"'
      register: gitlab_remove_query
      failed_when: "'gitlabhq_production' in (gitlab_remove_query.stdout | from_json)"

    - name: Perform gitlab restore
      ansible.builtin.command: /usr/local/bin/gitlab-restore

    - name: Verify gitlab database restore
      ansible.builtin.command: 'gitlab-psql -d postgres -t -c "select json_agg(datname) from pg_database"'
      register: gitlab_verify_query
      failed_when: "'gitlabhq_production' not in (gitlab_verify_query.stdout | from_json)"

    - name: Verify status command after restore
      ansible.builtin.command: gitlab-ctl status

    - name: Verify frontpage redirect
      ansible.builtin.uri:
        url: http://localhost
        follow_redirects: none
        status_code: 302
      register: _frontpage_redirect
      until: _frontpage_redirect is not failed
      retries: 12
      delay: 15

    - name: Verify frontpage content
      ansible.builtin.uri:
        url: http://localhost
        status_code: 200
      register: _frontpage_content
      until: _frontpage_content is not failed
      retries: 12
      delay: 15
