---
name: release

env:
  DEVBOX_VERSION: ${{ vars.DEVBOX_VERSION }}

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          devbox-version: ${{ vars.DEVBOX_VERSION }}

      - name: Release collection
        run: devbox run -- make publish
        env:
          GALAXY_API_KEY: "${{ secrets.GALAXY_API_KEY }}"
          GITHUB_REPOSITORY: "${{ github.repository }}"
